version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=spotifyData