spring:
  data:
    mongodb:
      host: mongo
      database: spotifyData
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token
            authorization-uri: https://accounts.spotify.com/authorize
            user-info-uri: https://api.spotify.com/v1/me